server:
  port: 8080
  servlet:
    context-path: /

spring:
  ai:
    openai:
      api-key: sk-IjBqzwzoN1mF147ur4XjD5rRuosQHaH9qTWrewdmT2BoLbq3
      base-url: https://api.gpts.vin
      chat:
        options:
          model: gpt-4o
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aidb
    username: aidb
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml